# Generated by Django 4.2.1 on 2023-05-16 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('I', 'Indefinido')], default='I', max_length=1)),
                ('birth_date', models.DateField()),
                ('average_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('total_donations', models.PositiveIntegerField(default=0)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
