# Generated by Django 4.2.1 on 2023-05-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodplus_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
