# Generated by Django 4.2.1 on 2023-05-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodplus_v1', '0003_alter_bloodtype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodplus_v1.bloodtype'),
        ),
    ]
