# Generated by Django 4.2.1 on 2023-05-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodplus_v1', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DONADOR', 'Donador'), ('SOLICITADOR', 'Solicitador')], default='ADMIN', max_length=50),
        ),
    ]
